"""initial canonical schema

Revision ID: 3972007fc95b
Revises: 
Create Date: 2026-09-13 18:50:35.991802+00:00
"""
from alembic import op
import sqlalchemy as sa


revision = '3972007fc95b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_audit_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('league', sa.String(length=16), nullable=False),
    sa.Column('dataset_version', sa.String(length=32), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('n_violations', sa.Integer(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('report_hash', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_audit_reports_dataset_version'), 'data_audit_reports', ['dataset_version'], unique=False)
    op.create_table('experiments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('experiment_id', sa.String(length=32), nullable=False),
    sa.Column('hypothesis', sa.Text(), nullable=False),
    sa.Column('league', sa.String(length=16), nullable=False),
    sa.Column('seasons', sa.JSON(), nullable=False),
    sa.Column('target', sa.String(length=64), nullable=False),
    sa.Column('conditions', sa.JSON(), nullable=False),
    sa.Column('n_eligible', sa.Integer(), nullable=False),
    sa.Column('n_signals', sa.Integer(), nullable=False),
    sa.Column('n_successes', sa.Integer(), nullable=False),
    sa.Column('signal_frequency', sa.Float(), nullable=False),
    sa.Column('baseline', sa.Float(), nullable=False),
    sa.Column('hit_rate', sa.Float(), nullable=False),
    sa.Column('absolute_uplift', sa.Float(), nullable=False),
    sa.Column('relative_uplift', sa.Float(), nullable=False),
    sa.Column('ci95_low', sa.Float(), nullable=False),
    sa.Column('ci95_high', sa.Float(), nullable=False),
    sa.Column('z', sa.Float(), nullable=False),
    sa.Column('per_season', sa.JSON(), nullable=False),
    sa.Column('per_team_concentration', sa.JSON(), nullable=False),
    sa.Column('dataset_version', sa.String(length=32), nullable=False),
    sa.Column('feature_versions', sa.JSON(), nullable=False),
    sa.Column('environment_lock', sa.JSON(), nullable=False),
    sa.Column('policy_version', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('result_hash', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_experiments_dataset_version'), 'experiments', ['dataset_version'], unique=False)
    op.create_index(op.f('ix_experiments_experiment_id'), 'experiments', ['experiment_id'], unique=True)
    op.create_index(op.f('ix_experiments_result_hash'), 'experiments', ['result_hash'], unique=False)
    op.create_table('feature_definitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('feature_id', sa.String(length=64), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('family', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('window', sa.Integer(), nullable=True),
    sa.Column('scope', sa.String(length=16), nullable=False),
    sa.Column('season_transition', sa.String(length=24), nullable=False),
    sa.Column('minimum_history', sa.Integer(), nullable=False),
    sa.Column('missing_data_policy', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('leakage_test_passed', sa.Boolean(), nullable=False),
    sa.Column('definition_hash', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('feature_id', 'version', name='uq_feature_version')
    )
    op.create_index(op.f('ix_feature_definitions_feature_id'), 'feature_definitions', ['feature_id'], unique=False)
    op.create_table('holdout_ledger',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('league', sa.String(length=16), nullable=False),
    sa.Column('season', sa.String(length=16), nullable=False),
    sa.Column('block', sa.String(length=16), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('opened_by', sa.String(length=128), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.CheckConstraint("block in ('DISCOVERY','VALIDATION','TEST')", name='ck_holdout_block'),
    sa.CheckConstraint("state in ('UNSEEN','SEEN')", name='ck_holdout_state'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('league', 'season', name='uq_holdout_season')
    )
    op.create_index(op.f('ix_holdout_ledger_league'), 'holdout_ledger', ['league'], unique=False)
    op.create_table('sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('canonical_name', sa.String(length=128), nullable=False),
    sa.Column('country', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('canonical_name')
    )
    op.create_table('fixtures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('league', sa.String(length=16), nullable=False),
    sa.Column('season', sa.String(length=16), nullable=False),
    sa.Column('match_date', sa.Date(), nullable=False),
    sa.Column('kickoff_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('kickoff_precision', sa.String(length=16), nullable=False),
    sa.Column('sync_batch', sa.Integer(), nullable=False),
    sa.Column('home_team_id', sa.Integer(), nullable=False),
    sa.Column('away_team_id', sa.Integer(), nullable=False),
    sa.Column('fthg', sa.Integer(), nullable=True),
    sa.Column('ftag', sa.Integer(), nullable=True),
    sa.Column('ftr', sa.String(length=1), nullable=True),
    sa.Column('hthg', sa.Integer(), nullable=True),
    sa.Column('htag', sa.Integer(), nullable=True),
    sa.Column('htr', sa.String(length=1), nullable=True),
    sa.Column('stats', sa.JSON(), nullable=False),
    sa.Column('source_lineage', sa.JSON(), nullable=False),
    sa.Column('quality_grade', sa.String(length=8), nullable=False),
    sa.Column('conflict', sa.Boolean(), nullable=False),
    sa.Column('dataset_version', sa.String(length=32), nullable=False),
    sa.CheckConstraint("kickoff_precision in ('EXACT','DATE_ONLY')", name='ck_kickoff_precision'),
    sa.CheckConstraint('home_team_id <> away_team_id', name='ck_not_self_match'),
    sa.ForeignKeyConstraint(['away_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['home_team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('league', 'season', 'home_team_id', 'away_team_id', name='uq_fixture_identity')
    )
    op.create_index(op.f('ix_fixtures_away_team_id'), 'fixtures', ['away_team_id'], unique=False)
    op.create_index(op.f('ix_fixtures_dataset_version'), 'fixtures', ['dataset_version'], unique=False)
    op.create_index(op.f('ix_fixtures_home_team_id'), 'fixtures', ['home_team_id'], unique=False)
    op.create_index(op.f('ix_fixtures_kickoff_utc'), 'fixtures', ['kickoff_utc'], unique=False)
    op.create_index(op.f('ix_fixtures_league'), 'fixtures', ['league'], unique=False)
    op.create_index(op.f('ix_fixtures_match_date'), 'fixtures', ['match_date'], unique=False)
    op.create_index(op.f('ix_fixtures_season'), 'fixtures', ['season'], unique=False)
    op.create_index(op.f('ix_fixtures_sync_batch'), 'fixtures', ['sync_batch'], unique=False)
    op.create_table('raw_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('league', sa.String(length=16), nullable=False),
    sa.Column('season', sa.String(length=16), nullable=False),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('n_rows', sa.Integer(), nullable=False),
    sa.Column('n_cols', sa.Integer(), nullable=False),
    sa.Column('origin', sa.Text(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'league', 'season', 'sha256', name='uq_raw_identity')
    )
    op.create_index(op.f('ix_raw_snapshots_sha256'), 'raw_snapshots', ['sha256'], unique=False)
    op.create_table('team_aliases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('source_code', sa.String(length=32), nullable=False),
    sa.Column('alias', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_code', 'alias', name='uq_alias_per_source')
    )
    op.create_index(op.f('ix_team_aliases_alias'), 'team_aliases', ['alias'], unique=False)
    op.create_table('source_conflicts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fixture_id', sa.Integer(), nullable=True),
    sa.Column('field', sa.String(length=64), nullable=False),
    sa.Column('values_by_source', sa.JSON(), nullable=False),
    sa.Column('resolution', sa.String(length=32), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['fixture_id'], ['fixtures.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('source_conflicts')
    op.drop_index(op.f('ix_team_aliases_alias'), table_name='team_aliases')
    op.drop_table('team_aliases')
    op.drop_index(op.f('ix_raw_snapshots_sha256'), table_name='raw_snapshots')
    op.drop_table('raw_snapshots')
    op.drop_index(op.f('ix_fixtures_sync_batch'), table_name='fixtures')
    op.drop_index(op.f('ix_fixtures_season'), table_name='fixtures')
    op.drop_index(op.f('ix_fixtures_match_date'), table_name='fixtures')
    op.drop_index(op.f('ix_fixtures_league'), table_name='fixtures')
    op.drop_index(op.f('ix_fixtures_kickoff_utc'), table_name='fixtures')
    op.drop_index(op.f('ix_fixtures_home_team_id'), table_name='fixtures')
    op.drop_index(op.f('ix_fixtures_dataset_version'), table_name='fixtures')
    op.drop_index(op.f('ix_fixtures_away_team_id'), table_name='fixtures')
    op.drop_table('fixtures')
    op.drop_table('teams')
    op.drop_table('sources')
    op.drop_index(op.f('ix_holdout_ledger_league'), table_name='holdout_ledger')
    op.drop_table('holdout_ledger')
    op.drop_index(op.f('ix_feature_definitions_feature_id'), table_name='feature_definitions')
    op.drop_table('feature_definitions')
    op.drop_index(op.f('ix_experiments_result_hash'), table_name='experiments')
    op.drop_index(op.f('ix_experiments_experiment_id'), table_name='experiments')
    op.drop_index(op.f('ix_experiments_dataset_version'), table_name='experiments')
    op.drop_table('experiments')
    op.drop_index(op.f('ix_data_audit_reports_dataset_version'), table_name='data_audit_reports')
    op.drop_table('data_audit_reports')
    # ### end Alembic commands ###
