"""hypothesis generator fields

Revision ID: 6cc626c77ca8
Revises: eb31da92ea90
Create Date: 2026-09-13 19:36:05.343321+00:00
"""
from alembic import op
import sqlalchemy as sa


revision = '6cc626c77ca8'
down_revision = 'eb31da92ea90'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('generation_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_key', sa.String(length=32), nullable=False),
    sa.Column('research_question', sa.Text(), nullable=False),
    sa.Column('league', sa.String(length=16), nullable=False),
    sa.Column('dataset_version', sa.String(length=32), nullable=False),
    sa.Column('search_policy_hash', sa.String(length=32), nullable=False),
    sa.Column('seed', sa.Integer(), nullable=False),
    sa.Column('mode_mix', sa.JSON(), nullable=False),
    sa.Column('n_pool', sa.Integer(), nullable=False),
    sa.Column('n_emitted', sa.Integer(), nullable=False),
    sa.Column('n_skipped', sa.Integer(), nullable=False),
    sa.Column('memory_verdicts', sa.JSON(), nullable=False),
    sa.Column('budget', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generation_runs_batch_key'), 'generation_runs', ['batch_key'], unique=True)
    op.create_index(op.f('ix_generation_runs_dataset_version'), 'generation_runs', ['dataset_version'], unique=False)
    op.add_column('hypothesis_registry', sa.Column('hypothesis_key', sa.String(length=320), nullable=True))
    op.add_column('hypothesis_registry', sa.Column('parent_hypothesis_key', sa.String(length=320), nullable=True))
    op.add_column('hypothesis_registry', sa.Column('htype', sa.String(length=24), nullable=True))
    op.add_column('hypothesis_registry', sa.Column('mode', sa.String(length=24), nullable=True))
    op.add_column('hypothesis_registry', sa.Column('complexity', sa.Integer(), nullable=True))
    op.add_column('hypothesis_registry', sa.Column('generation', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('hypothesis_registry', sa.Column('mutation_reason', sa.Text(), nullable=True))
    op.create_index(op.f('ix_hypothesis_registry_hypothesis_key'), 'hypothesis_registry', ['hypothesis_key'], unique=False)
    op.create_index(op.f('ix_hypothesis_registry_parent_hypothesis_key'), 'hypothesis_registry', ['parent_hypothesis_key'], unique=False)
    op.alter_column('hypothesis_registry', 'generation',
                    server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hypothesis_registry_parent_hypothesis_key'), table_name='hypothesis_registry')
    op.drop_index(op.f('ix_hypothesis_registry_hypothesis_key'), table_name='hypothesis_registry')
    op.drop_column('hypothesis_registry', 'mutation_reason')
    op.drop_column('hypothesis_registry', 'generation')
    op.drop_column('hypothesis_registry', 'complexity')
    op.drop_column('hypothesis_registry', 'mode')
    op.drop_column('hypothesis_registry', 'htype')
    op.drop_column('hypothesis_registry', 'parent_hypothesis_key')
    op.drop_column('hypothesis_registry', 'hypothesis_key')
    op.drop_index(op.f('ix_generation_runs_dataset_version'), table_name='generation_runs')
    op.drop_index(op.f('ix_generation_runs_batch_key'), table_name='generation_runs')
    op.drop_table('generation_runs')
    # ### end Alembic commands ###
