"""validation engine tables

Revision ID: dd6ec1eb455b
Revises: 3972007fc95b
Create Date: 2026-09-13 19:05:54.322421+00:00
"""
from alembic import op
import sqlalchemy as sa


revision = 'dd6ec1eb455b'
down_revision = '3972007fc95b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('search_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.String(length=32), nullable=False),
    sa.Column('research_question', sa.Text(), nullable=False),
    sa.Column('league', sa.String(length=16), nullable=False),
    sa.Column('seasons', sa.JSON(), nullable=False),
    sa.Column('n_candidates', sa.Integer(), nullable=False),
    sa.Column('n_negative_controls', sa.Integer(), nullable=False),
    sa.Column('dataset_version', sa.String(length=32), nullable=False),
    sa.Column('statistical_policy_hash', sa.String(length=32), nullable=False),
    sa.Column('null_world', sa.JSON(), nullable=False),
    sa.Column('fwer_threshold', sa.Float(), nullable=False),
    sa.Column('n_passing', sa.Integer(), nullable=False),
    sa.Column('fingerprint', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_search_batches_batch_id'), 'search_batches', ['batch_id'], unique=True)
    op.create_index(op.f('ix_search_batches_dataset_version'), 'search_batches', ['dataset_version'], unique=False)
    op.create_index(op.f('ix_search_batches_fingerprint'), 'search_batches', ['fingerprint'], unique=False)
    op.create_table('strategies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('strategy_id', sa.String(length=32), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('league', sa.String(length=16), nullable=False),
    sa.Column('target', sa.String(length=64), nullable=False),
    sa.Column('conditions', sa.JSON(), nullable=False),
    sa.Column('feature_versions', sa.JSON(), nullable=False),
    sa.Column('formula_hash', sa.String(length=32), nullable=False),
    sa.Column('strategy_hash', sa.String(length=32), nullable=False),
    sa.Column('qualification_policy_hash', sa.String(length=32), nullable=False),
    sa.Column('statistical_policy_hash', sa.String(length=32), nullable=False),
    sa.Column('seen_seasons', sa.JSON(), nullable=False),
    sa.Column('frozen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('stage', sa.String(length=24), nullable=False),
    sa.Column('strategy_class', sa.String(length=24), nullable=False),
    sa.Column('action', sa.String(length=16), nullable=True),
    sa.Column('park_kill_reason', sa.Text(), nullable=True),
    sa.Column('parent_version', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('strategy_id', 'version', name='uq_strategy_version')
    )
    op.create_index(op.f('ix_strategies_strategy_hash'), 'strategies', ['strategy_hash'], unique=False)
    op.create_index(op.f('ix_strategies_strategy_id'), 'strategies', ['strategy_id'], unique=False)
    op.create_table('validation_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.String(length=32), nullable=False),
    sa.Column('strategy_id', sa.String(length=32), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('strategy_hash', sa.String(length=32), nullable=False),
    sa.Column('batch_id', sa.String(length=32), nullable=True),
    sa.Column('oos_seasons', sa.JSON(), nullable=False),
    sa.Column('oos_validity', sa.String(length=24), nullable=False),
    sa.Column('outcome', sa.String(length=16), nullable=False),
    sa.Column('action', sa.String(length=16), nullable=False),
    sa.Column('strategy_class', sa.String(length=24), nullable=False),
    sa.Column('fwer_threshold', sa.Float(), nullable=True),
    sa.Column('criterion', sa.JSON(), nullable=False),
    sa.Column('discovery', sa.JSON(), nullable=False),
    sa.Column('oos', sa.JSON(), nullable=False),
    sa.Column('robustness', sa.JSON(), nullable=False),
    sa.Column('notes', sa.JSON(), nullable=False),
    sa.Column('run_hash', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_validation_runs_batch_id'), 'validation_runs', ['batch_id'], unique=False)
    op.create_index(op.f('ix_validation_runs_run_hash'), 'validation_runs', ['run_hash'], unique=False)
    op.create_index(op.f('ix_validation_runs_run_id'), 'validation_runs', ['run_id'], unique=True)
    op.create_index(op.f('ix_validation_runs_strategy_id'), 'validation_runs', ['strategy_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_validation_runs_strategy_id'), table_name='validation_runs')
    op.drop_index(op.f('ix_validation_runs_run_id'), table_name='validation_runs')
    op.drop_index(op.f('ix_validation_runs_run_hash'), table_name='validation_runs')
    op.drop_index(op.f('ix_validation_runs_batch_id'), table_name='validation_runs')
    op.drop_table('validation_runs')
    op.drop_index(op.f('ix_strategies_strategy_id'), table_name='strategies')
    op.drop_index(op.f('ix_strategies_strategy_hash'), table_name='strategies')
    op.drop_table('strategies')
    op.drop_index(op.f('ix_search_batches_fingerprint'), table_name='search_batches')
    op.drop_index(op.f('ix_search_batches_dataset_version'), table_name='search_batches')
    op.drop_index(op.f('ix_search_batches_batch_id'), table_name='search_batches')
    op.drop_table('search_batches')
    # ### end Alembic commands ###
