"""research memory tables

Revision ID: eb31da92ea90
Revises: 29ec83f57570
Create Date: 2026-09-13 19:20:14.319051+00:00
"""
from alembic import op
import sqlalchemy as sa


revision = 'eb31da92ea90'
down_revision = '29ec83f57570'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('decision_audit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject_type', sa.String(length=32), nullable=False),
    sa.Column('subject_id', sa.String(length=48), nullable=False),
    sa.Column('machine_recommendation', sa.String(length=32), nullable=False),
    sa.Column('human_override', sa.String(length=32), nullable=True),
    sa.Column('actor', sa.String(length=64), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_decision_audit_subject_id'), 'decision_audit', ['subject_id'], unique=False)
    op.create_table('exhausted_regions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('region_key', sa.String(length=160), nullable=False),
    sa.Column('league', sa.String(length=16), nullable=False),
    sa.Column('dataset_version', sa.String(length=32), nullable=False),
    sa.Column('hypotheses_tested', sa.Integer(), nullable=False),
    sa.Column('best_abs_z', sa.Float(), nullable=False),
    sa.Column('batch_threshold', sa.Float(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('region_key', 'dataset_version', name='uq_region_dataset')
    )
    op.create_index(op.f('ix_exhausted_regions_region_key'), 'exhausted_regions', ['region_key'], unique=False)
    op.create_table('hypothesis_registry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hypothesis_id', sa.String(length=32), nullable=False),
    sa.Column('league', sa.String(length=16), nullable=False),
    sa.Column('seasons', sa.JSON(), nullable=False),
    sa.Column('target', sa.String(length=64), nullable=False),
    sa.Column('conditions', sa.JSON(), nullable=False),
    sa.Column('feature_versions', sa.JSON(), nullable=False),
    sa.Column('exact_fingerprint', sa.String(length=32), nullable=False),
    sa.Column('semantic_fingerprint', sa.String(length=32), nullable=False),
    sa.Column('signal_fingerprint', sa.String(length=32), nullable=True),
    sa.Column('region_key', sa.String(length=160), nullable=False),
    sa.Column('origin', sa.String(length=32), nullable=False),
    sa.Column('batch_id', sa.String(length=32), nullable=True),
    sa.Column('dataset_version', sa.String(length=32), nullable=False),
    sa.Column('n_signals', sa.Integer(), nullable=True),
    sa.Column('baseline', sa.Float(), nullable=True),
    sa.Column('hit_rate', sa.Float(), nullable=True),
    sa.Column('absolute_uplift', sa.Float(), nullable=True),
    sa.Column('z', sa.Float(), nullable=True),
    sa.Column('passed_batch_threshold', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('strategy_id', sa.String(length=32), nullable=True),
    sa.Column('times_seen', sa.Integer(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exact_fingerprint', name='uq_exact_fingerprint')
    )
    op.create_index(op.f('ix_hypothesis_registry_batch_id'), 'hypothesis_registry', ['batch_id'], unique=False)
    op.create_index(op.f('ix_hypothesis_registry_dataset_version'), 'hypothesis_registry', ['dataset_version'], unique=False)
    op.create_index(op.f('ix_hypothesis_registry_exact_fingerprint'), 'hypothesis_registry', ['exact_fingerprint'], unique=False)
    op.create_index(op.f('ix_hypothesis_registry_hypothesis_id'), 'hypothesis_registry', ['hypothesis_id'], unique=True)
    op.create_index(op.f('ix_hypothesis_registry_league'), 'hypothesis_registry', ['league'], unique=False)
    op.create_index(op.f('ix_hypothesis_registry_region_key'), 'hypothesis_registry', ['region_key'], unique=False)
    op.create_index(op.f('ix_hypothesis_registry_semantic_fingerprint'), 'hypothesis_registry', ['semantic_fingerprint'], unique=False)
    op.create_index(op.f('ix_hypothesis_registry_signal_fingerprint'), 'hypothesis_registry', ['signal_fingerprint'], unique=False)
    op.create_index(op.f('ix_hypothesis_registry_strategy_id'), 'hypothesis_registry', ['strategy_id'], unique=False)
    op.create_index(op.f('ix_hypothesis_registry_target'), 'hypothesis_registry', ['target'], unique=False)
    op.create_table('kill_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('strategy_id', sa.String(length=32), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=48), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('policy_version', sa.String(length=48), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kill_records_strategy_id'), 'kill_records', ['strategy_id'], unique=False)
    op.create_table('meta_feature_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('feature_id', sa.String(length=64), nullable=False),
    sa.Column('target', sa.String(length=64), nullable=False),
    sa.Column('hypotheses', sa.Integer(), nullable=False),
    sa.Column('passed_threshold', sa.Integer(), nullable=False),
    sa.Column('candidates', sa.Integer(), nullable=False),
    sa.Column('robust', sa.Integer(), nullable=False),
    sa.Column('killed', sa.Integer(), nullable=False),
    sa.Column('parked', sa.Integer(), nullable=False),
    sa.Column('best_abs_z', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('feature_id', 'target', name='uq_meta_feature_target')
    )
    op.create_index(op.f('ix_meta_feature_stats_feature_id'), 'meta_feature_stats', ['feature_id'], unique=False)
    op.create_table('park_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('strategy_id', sa.String(length=32), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('revival_condition', sa.Text(), nullable=False),
    sa.Column('min_new_fixtures', sa.Integer(), nullable=False),
    sa.Column('fixtures_at_park', sa.Integer(), nullable=False),
    sa.Column('review_after', sa.DateTime(timezone=True), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('revived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_park_records_strategy_id'), 'park_records', ['strategy_id'], unique=False)
    op.create_table('strategy_families',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('family_id', sa.String(length=32), nullable=False),
    sa.Column('label', sa.String(length=160), nullable=False),
    sa.Column('members', sa.JSON(), nullable=False),
    sa.Column('max_pairwise_jaccard', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_strategy_families_family_id'), 'strategy_families', ['family_id'], unique=True)
    op.create_table('strategy_signal_sets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('strategy_id', sa.String(length=32), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('dataset_version', sa.String(length=32), nullable=False),
    sa.Column('fixture_ids', sa.JSON(), nullable=False),
    sa.Column('signal_fingerprint', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_strategy_signal_sets_signal_fingerprint'), 'strategy_signal_sets', ['signal_fingerprint'], unique=False)
    op.create_index(op.f('ix_strategy_signal_sets_strategy_id'), 'strategy_signal_sets', ['strategy_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_strategy_signal_sets_strategy_id'), table_name='strategy_signal_sets')
    op.drop_index(op.f('ix_strategy_signal_sets_signal_fingerprint'), table_name='strategy_signal_sets')
    op.drop_table('strategy_signal_sets')
    op.drop_index(op.f('ix_strategy_families_family_id'), table_name='strategy_families')
    op.drop_table('strategy_families')
    op.drop_index(op.f('ix_park_records_strategy_id'), table_name='park_records')
    op.drop_table('park_records')
    op.drop_index(op.f('ix_meta_feature_stats_feature_id'), table_name='meta_feature_stats')
    op.drop_table('meta_feature_stats')
    op.drop_index(op.f('ix_kill_records_strategy_id'), table_name='kill_records')
    op.drop_table('kill_records')
    op.drop_index(op.f('ix_hypothesis_registry_target'), table_name='hypothesis_registry')
    op.drop_index(op.f('ix_hypothesis_registry_strategy_id'), table_name='hypothesis_registry')
    op.drop_index(op.f('ix_hypothesis_registry_signal_fingerprint'), table_name='hypothesis_registry')
    op.drop_index(op.f('ix_hypothesis_registry_semantic_fingerprint'), table_name='hypothesis_registry')
    op.drop_index(op.f('ix_hypothesis_registry_region_key'), table_name='hypothesis_registry')
    op.drop_index(op.f('ix_hypothesis_registry_league'), table_name='hypothesis_registry')
    op.drop_index(op.f('ix_hypothesis_registry_hypothesis_id'), table_name='hypothesis_registry')
    op.drop_index(op.f('ix_hypothesis_registry_exact_fingerprint'), table_name='hypothesis_registry')
    op.drop_index(op.f('ix_hypothesis_registry_dataset_version'), table_name='hypothesis_registry')
    op.drop_index(op.f('ix_hypothesis_registry_batch_id'), table_name='hypothesis_registry')
    op.drop_table('hypothesis_registry')
    op.drop_index(op.f('ix_exhausted_regions_region_key'), table_name='exhausted_regions')
    op.drop_table('exhausted_regions')
    op.drop_index(op.f('ix_decision_audit_subject_id'), table_name='decision_audit')
    op.drop_table('decision_audit')
    # ### end Alembic commands ###
